AWSTemplateFormatVersion: 2010-09-09

Description: |
  Serverless application resources

Resources:
  ServerlessLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ServerlessLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"

  ServerlessLambdaRolePolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref ServerlessLambdaRole
      PolicyName: ServerlessLambdaRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - "*"

  ServerlessFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: websocket-serverless-lambda
      Handler: ca.blockbreak.serverless.App
      Code:
        S3Bucket: !ImportValue CodeDeployS3Bucket
        S3Key: serverless/serverless-1.0-SNAPSHOT.jar
      Runtime: java25
      Timeout: 5
      Role: !GetAtt ServerlessLambdaRole.Arn

  ServerlessAPIGateway:
    Type: "AWS::ApiGatewayV2::Api"
    Properties:
      Name: ServerlessWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      ApiKeySelectionExpression: $request.header.x-api-key
