apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: block-break
spec:
  ports:
    - protocol: TCP
      port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: block-break
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - server
      containers:
        - name: mongodb
          image: mongo:8.2
          resources:
             requests:
               memory: "1048Mi"
               cpu: "500m"
             limits:
               memory: "2048Mi"
               cpu: "1000m"
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            ## This fixes MongoDB crashing silently after 30s with error 139 because of "tcmalloc"
            - name: GLIBC_TUNABLES
              value: "glibc.pthread.rseq=1"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              ## kubectl create secret generic -n block-break mongodb-db-secret --from-literal=password=ChangeMe!
              valueFrom:
                secretKeyRef:
                  name: mongodb-db-secret
                  key: password
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-storage-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-break-mongodb-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: database-storage
  csi:
    driver: iscsi.csi.k8s.io
    volumeHandle: iscsi-192.168.7.227-block-break:mongodb-1  # Must be globally unique
    volumeAttributes:
      targetPortal: 192.168.7.227:3260
      portals: "[]"
      iqn: iqn.2026-09.block-break:mongodb
      lun: "1"
      iscsiInterface: "default"
      discovery: "true"
      discoveryCHAPAuth: "true"
      sessionCHAPAuth: "false"
      fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-storage-pvc
  namespace: block-break
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: database-storage
  volumeName: block-break-mongodb-storage-pv
  resources:
    requests:
      storage: 10Gi
