apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: block-break
  annotations:
      kube-vip.io/loadbalancerIPs: "10.214.0.13"
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
  namespace: block-break
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:18.4
          resources:
             requests:
               memory: "1024Mi"
               cpu: "500m"
             limits:
               memory: "2048Mi"
               cpu: "1000m"
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_PASSWORD
              ## kubectl create secret generic -n block-break postgresql-db-secret --from-literal=password=ChangeMe!
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-secret
                  key: password
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgresql-storage
        namespace: block-break
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
