services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - /mnt/External/BBDevel/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  database-postgresql:
    image: postgres:15-alpine
    container_name: database-postgresql
    environment:
      POSTGRES_PASSWORD: sshsecret
    volumes:
      - /mnt/External/BBDevel/db-postgresql:/var/lib/postgresql/data

  database-mysql:
    image: mariadb:12.2
    container_name: database-mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - /mnt/External/BBDevel/db-mysql:/var/lib/mysql:Z

  database-redis:
    image: redis:8.6-alpine
    container_name: database-redis

  database-mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: shhsecret
    volumes:
      - /mnt/External/BBDevel/db-mongo:/data/db

  blockbreak-devel:
    build:
      dockerfile_inline: |
        FROM ubuntu:resolute
        ## Using Ubuntu because a company backs it.

        ## Update packages to install
        RUN apt-get update

        ## Install ssh server first.  Fingerprint is less likely to change if ssh server is installed first.
        RUN apt-get install -y openssh-server
        RUN service ssh start

        #install docker tools
        RUN apt-get install -y docker.io docker-buildx docker-compose-v2

        ## add user, don't create home, will use nfs for home directories
        ## group docker(102) is _ssh(102) on ubuntu
        RUN useradd --shell /bin/bash -G users,_ssh,systemd-journal -u 3000 amills
        RUN mkdir /home/amills
        RUN chown amills:users /home/amills

        ## install extra programs
        RUN apt-get install -y sudo unzip git less gpg

        RUN echo "amills ALL=(ALL:ALL) NOPASSWD:ALL\n" >/etc/sudoers.d/devel

        ## install packages aws cli
        RUN wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        RUN unzip awscli-exe-linux-x86_64.zip
        RUN sudo ./aws/install

        ## install packages java
        RUN wget -O - https://apt.corretto.aws/corretto.key | gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg
        RUN echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | tee /etc/apt/sources.list.d/corretto.list

        RUN sudo apt-get update
        RUN sudo apt-get install -y java-25-amazon-corretto-jdk

        EXPOSE 22

        CMD ["/usr/sbin/sshd", "-D"]

    container_name: blockbreak-devel
    hostname: blockbreak-devel
    ports:
      - "2024:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/External/BBDevel/home/amills/:/home/amills
