name: Build Website
on:
  push:
    branches:
      - main
      - feature/**

permissions:
  id-token: write
  contents: read

concurrency:
  group: website
  cancel-in-progress: true

jobs:
  build-website:
    environment:
      name: Staging
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24" # Specify your Node version

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build website
        run: npm run build

      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'website/dist'
