name: Deploy server and serverless
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    paths:
      - .github/workflows/**
      - server/**
      - serverless/**

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

jobs:
  test-server:
    name: Test server
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/test-maven.yml
    with:
      dir: server

  build-server:
    name: Build server
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/build-maven.yml
    with:
      dir: server

  test-serverless:
    name: Test serverless
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/test-maven.yml
    with:
      dir: serverless

  build-serverless:
    name: Build serverless
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/build-maven.yml
    with:
      dir: serverless

  deploy-server:
    name: Deploy server
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs:
      - test-server
      - build-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: pull-request-server
          path: server-target/

      - name: Copy jar file
        run: |
          mkdir -p ./server/src/main/resources/image/target
          cp server-target/*.jar ./server/src/main/resources/image/target

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically generated by GitHub

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/block-break-server
          tags: |
              type=sha
              type=raw,value=pr-${{ github.event.pull_request.number }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: ./server/src/main/resources/image
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/block-break-server
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy-serverless:
    name: Deploy serverless
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs:
      - test-serverless
      - build-serverless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: pull-request-serverless
          path: serverless-target/

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload artifact to S3 bucket
        run: |
            aws s3 cp ./serverless-target/ \
            s3://${{ vars.S3_DEPLOY_BUCKET }}/serverless/pr-${{ github.event.pull_request.number }}/ \
            --recursive --exclude "*/*" --include "*.jar"

  deploy-staging-server:
    name: Deploy staging server
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically generated by GitHub

      - name: Tag PR tag with staging tag
        run: |
          docker buildx imagetools create \
          ghcr.io/${{ github.repository_owner }}/block-break-server:pr-${{ github.event.pull_request.number }} \
          --tag ghcr.io/${{ github.repository_owner }}/block-break-server:staging \

      - name: Remove image
        uses: dataaxiom/ghcr-cleanup-action@v1 ## no offical action to remove tags, docker does not have an option to
                                               ## remove remote tags either
        with:
          package: block-break-server
          delete-tags: pr-${{ github.event.pull_request.number }}

  deploy-staging-serverless:
    name: Deploy staging serverless
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload artifact to S3 staging folder
        run: |
            aws s3 cp \
            s3://${{ vars.s3_deploy_bucket }}/serverless/pr-${{ github.event.pull_request.number }}/ \
            s3://${{ vars.s3_deploy_bucket }}/serverless/staging/ \
            --recursive

      - name: Deploy api gateway
        run: |
            echo "Deploy api gateway"

      - name: Remove S3 PR folder
        run: |
            aws s3 rm \
            s3://${{ vars.s3_deploy_bucket }}/serverless/pr-${{ github.event.pull_request.number }}/ \
            --recursive

  deploy-production-server:
    name: Deploy production server
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    needs: deploy-staging-server
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically generated by GitHub

      - name: Tag PR tag with staging tag
        run: |
          docker buildx imagetools create \
          ghcr.io/${{ github.repository_owner }}/block-break-server:staging \
          --tag ghcr.io/${{ github.repository_owner }}/block-break-server:production \
          docker buildx imagetools create \
          ghcr.io/${{ github.repository_owner }}/block-break-server:staging \
          --tag ghcr.io/${{ github.repository_owner }}/block-break-server:latest \

  deploy-production-serverless:
    name: Deploy production serverless
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    needs: deploy-staging-serverless
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload artifact to S3 production folder
        run: |
            aws s3 cp \
            s3://${{ vars.s3_deploy_bucket }}/serverless/staging/ \
            s3://${{ vars.s3_deploy_bucket }}/serverless/production/ \
            --recursive

      - name: Deploy api gateway
        run: |
            echo "Deploy api gateway"

  cleanup:
    name: Cleanup
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
    needs:
      - deploy-staging-server
      - deploy-staging-serverless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Remove S3 PR folder
        run: |
            aws s3 rm \
            s3://${{ vars.s3_deploy_bucket }}/serverless/pr-${{ github.event.pull_request.number }}/ \
            --recursive

      - name: Remove image
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-tags: pr-${{ github.event.pull_request.number }}

      - run: |
          echo "Clean up, clean up, everybody clean up... ${{ github.event.pull_request.number }}"
