on:
  workflow_call:
    inputs:
      dir:
        description: Directory
        required: true
        type: string
      aws_region:
        description: AWS Region
        required: true
        type: string
      s3_deploy_bucket:
        description: S3 deploy bucket
        required: true
        type: string
    secrets:
      iam_role_github:
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.dir }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: pull-request-${{ inputs.dir }}

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.iam_role_github }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ inputs.aws_region }}

      - name: Upload artifact to S3 bucket
        run: |
            aws s3 cp ${{ inputs.dir }}/dist/ s3://${{ inputs.s3_deploy_bucket }}/${{ inputs.dir }}/pr-${{ github.event.pull_request.number }}/ --recursive
