name: Deploy server and serverless
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    paths:
      - .github/workflows/**
      - server/**
      - serverless/**

permissions:
  id-token: write
  contents: read

jobs:
  test-server:
    name: Test server
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/test-maven.yml
    with:
      dir: server

  build-server:
    name: Build server
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/build-maven.yml
    with:
      dir: server

  test-serverless:
    name: Test serverless
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/test-maven.yml
    with:
      dir: serverless

  build-serverless:
    name: Build serverless
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/build-maven.yml
    with:
      dir: serverless

  deploy-server:
    name: Deploy server
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs:
      - test-server
      - build-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: pull-request-server
          path: server-target/

      - name: Copy jar file
        run: |
          ls ./server-target/
          ls ./server/src/main/resources/image/
          mkdir -p ./server/src/main/resources/image/target
          cp server-target/*.jar ./server/src/main/resources/image/target
          ls ./server/src/main/resources/image/target

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically generated by GitHub

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/server
          tags: |
              type=sha
              type=raw,value=pr-${{ github.event.pull_request.number }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: ./server/src/main/resources/images
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/server
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy-serverless:
    name: Deploy serverless
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs:
      - test-serverless
      - build-serverless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: pull-request-serverless
          path: serverless-target/

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.iam_role_github }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload artifact to S3 bucket
        run: |
            aws s3 cp ../serverless-target/*.jar s3://${{ vars.s3_deploy_bucket }}/serverless/pr-${{ github.event.pull_request.number }}/

  # cleanup:
  #   name: Cleanup
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
  #   needs:
  #     - deploy-staging-server
  #     - deploy-staging-serverless
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v7

  #     - name: Get AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v6
  #       with:
  #         role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
  #         role-session-name: GitHub-Action-Role
  #         aws-region: ${{ vars.AWS_REGION }}

  #     - name: Remove S3 PR folder
  #       run: |
  #           aws s3 rm \
  #           s3://${{ vars.s3_deploy_bucket }}/serverless/pr-${{ github.event.pull_request.number }}/ \
  #           --recursive

  #     - name: Remove image
  #       run: |
  #           ## need to consider this, if it's promoted, remove tag, if it's not, remove tag and image
  #           # or just remove the tag and clean up unused images another way
  #           echo "Remove container image tag"

  #     - run: |
  #         echo "Clean up, clean up, everybody clean up... ${{ github.event.pull_request.number }}"
