name: Deploy website
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    paths:
      - .github/workflows/**
      - website/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - website/**

permissions:
  id-token: write
  contents: read

## concurrency should be on a per job level
# concurrency:
#   group: ${{ github.event_name }}-${{ github.event.action}}-${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  test-website:
    name: Test website
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/test-npm.yml
    with:
      dir: website

  build-website:
    name: Build website
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/build-npm.yml
    with:
      dir: website

  deploy-website:
    name: Deploy website
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs:
      - test-website
      - build-website
    uses: ./.github/workflows/deploy-npm.yml
    with:
      dir: website
      aws_region: ${{ vars.AWS_REGION }}
      s3_deploy_bucket: ${{ vars.S3_DEPLOY_BUCKET }}
    secrets:
      iam_role_github: ${{ secrets.IAMROLE_GITHUB }}

  deploy-staging-website:
    name: Deploy staging website
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.iam_role_github }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.aws_region }}

      - name: Upload artifact to S3 staging folder
        run: |
            aws s3 cp \
            s3://${{ vars.s3_deploy_bucket }}/website/pr-${{ github.event.pull_request.number }}/ \
            s3://${{ vars.s3_deploy_bucket }}/website/staging/ \
            --recursive

      - name: Upload artifact to S3 staging bucket
        run: |
            aws s3 cp \
            s3://${{ vars.s3_deploy_bucket }}/website/pr-${{ github.event.pull_request.number }}/ \
            s3://${{ env.s3_bucket }}/ \
            --recursive

  deploy-production-website:
    name: Deploy production website
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: deploy-staging-website
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.iam_role_github }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.aws_region }}

      - name: Upload artifact to S3 production folder
        run: |
            aws s3 cp \
            s3://${{ vars.s3_deploy_bucket }}/website/staging/ \
            s3://${{ vars.s3_deploy_bucket }}/website/production/ \
            --recursive

      - name: Upload artifact to S3 staging bucket
        run: |
            aws s3 cp \
            s3://${{ vars.s3_deploy_bucket }}/website/production/ \
            s3://${{ env.s3_bucket }}/ \
            --recursive

  cleanup:
    name: Cleanup
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Remove S3 PR folder
        run: |
          echo "Clean up, clean up, everybody clean up... ${{ github.event.pull_request.number }}"
            aws s3 rm s3://${{ vars.s3_deploy_bucket }}/${{ inputs.dir }}/pr-${{ github.event.pull_request.number }}/ --recursive
