on:
  workflow_call:
    inputs:
      dir:
        description: Directory
        required: true
        type: string
      stage:
        description: Stage of the deployment process
        required: true
        type: string

jobs:
  test:
    name: Deploy ${{ inputs.dir }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: production-${{ inputs.dir }}

      - name: Run deploy
        run: echo "Deploy ${{ inputs.stage }} website ${{ github.event.pull_request.number }}"
