name: Feature branch, client server
on:
  push:
    branches:
      - feature/**
    paths:
      - server

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-client:
    name: Test server
    runs-on: ubuntu-latest
    steps:
      - uses: ./templates/test-maven.yml
        with:
          dir: server
