name: Feature branch, client code
on:
  push:
    branches:
      - feature/**
    paths:
      - .github/workflows/**
      - client/**

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-client:
    name: Test client
    uses: ./.github/workflows/test-npm.yml
    with:
      dir: client
