name: Feature branch, client server
on:
  push:
    branches:
      - feature/**
    paths:
      - serverless/**

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-serverless:
    name: Test serverless
    uses: ./.github/workflows/templates/test-maven.yml
    with:
      dir: server
