name: Feature branch, website code
on:
  push:
    branches:
      - feature/**
    # paths:
    #   - website

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-website:
    name: Test website
    runs-on: ubuntu-latest
    steps:
      - uses: ./templates/test-npm.yml
        with:
          dir: website
