name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main
    paths:
      - app
      - client
      - server
      - serverless
      - website

jobs:
  ## CI: Run tests
  test-app:
    name: Test app
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v7

  test-client:
    name: Test client
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: client/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run test

  ## CD: Run builds
  build-app:
    name: Build app artifact
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v7
      # - name: Upload app artifact
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: production-ready-app
      #     path: ./dist/

  build-client:
    name: Build client artifact
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: client/package-lock.json
      - run: npm ci
      - run: npm run build
      - name: Upload app artifact
        uses: actions/upload-artifact@v7
        with:
          name: production-client
          path: ./dist/

  ## CD: Deploy to staging
  deploy-staging:
    name: Deploy to staging
    needs:
      - build-app
      - build-client
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      # - name: Download client
      #   uses: actions/download-artifact@v8
      #   with:
      #     name: production-app
      - name: Download client
        uses: actions/download-artifact@v8
        with:
          name: production-client
      - name: Deploy to staging
        run: echo "Deploy to staging"

  ## CD: Deploy to production
  deploy-production:
    name: Deploy to production
    needs: deploy-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Download client
        uses: actions/download-artifact@v8
        with:
          name: production-client
      - name: Deploy to production
        run: echo "Deploy to production"

  # Leaving this here in case we need it in the future
  cleanup:
    name: Cleanup
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Clean up, clean up, everybody clean up..."
